version: "3.3"

services:
  front:
    container_name: reacttest
    image: reacttest
    restart: always
    ports:
      - "3000:3000"

  back:
    container_name: back
    build: .
    restart: always
    ports:
      - "4001:4001"
    links:
      - mongo:mongo
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run dev"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mysql

volumes:
  mongo: