version: "3.3"

services:
  front:
    container_name: reacttest
    image: reacttest
    restart: always
    ports:
      - "3000:3000"

  back:
    container_name: back
    build: .
    restart: always
    ports:
      - "4001:4001"
    links:
      - mysql:mysql
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run dev"

  mysql:
    container_name: mysql
    image: mysql #this image must be built before docker-compose up
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: